# 路径配置
session_path: "session"  # 会话存档路径
log_path: "logs"        # 日志文件路径
export_path: "export"   # 导出文件路径
face_image_path: "imgs" # 人脸图片路径

# 基本配置
multi_session: true     # 是否允许多会话
tui_max_height: 25      # TUI界面最大高度
mask_acc: true         # 是否隐藏账号信息
fetch_uploaded_face: true  # 是否获取已上传的人脸图片

# 作业配置
work:
  enable: true         # 是否启用作业功能
  wait: 15            # 作业完成后等待时间(秒)
  export: false       # 是否导出作业
  fallback_save: true # 是否保存未完成的作业
  fallback_fuzzer: true  # 是否启用模糊匹配

# 视频配置
video:
  enable: true        # 是否启用视频功能
  wait: 15           # 视频完成后等待时间(秒)
  speed: 2.0         # 视频播放速度
  report_rate: 1     # 视频上报频率(秒)

# 文档配置
document:
  enable: true       # 是否启用文档功能
  wait: 15          # 文档完成后等待时间(秒)

# 考试配置
exam:
  enable: true      # 是否启用考试功能
  confirm_submit: true  # 是否确认交卷
  fallback_fuzzer: true  # 是否启用模糊匹配
  persubmit_delay: 1    # 每题提交延迟(秒)

# 搜索器配置
searchers:
  - "cxmooc"        # 超星慕课
  - "cxmooc-tiku"   # 超星慕课题库
  - "tampermonkey"  # Tampermonkey
  - "chaoxing"      # 超星
  - "chaoxing-tiku" # 超星题库